name: Prune old statuses

on:
  workflow_dispatch:
  schedule:
    - cron: '33 18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install requests
      - name: call prune script
        env:
          GOTOSOCIAL_ACCESS_TOKEN: ${{ secrets.GOTOSOCIAL_ACCESS_TOKEN }}
        run: python scripts/prune_old_statuses.py
